#!/usr/bin/env lua

if io.open("tests/keys/config") == nil then
    print("You first need to generate test keys.")
    print("To do so, run on your host machine ...")
    print("")
    print("  ./tests/generate-keys.sh")
    print("")
    print("... and retry")

    return
end

if arg[1] == nil then
    print(string.format("usage: %s <test peer ID>", arg[0]))

    return
end

local id = tonumber(arg[1])
local mode = arg[2] or 'unknown'
assert(id)

function execf(...)
    local cmd = string.format(...)
    print("\x1b[1;30m$ " .. cmd .. "\x1b[0m")
    return os.execute(cmd)
end

execf("rm -f /tmp/log")
execf("make")
print(string.rep('-', 80))

--execf("cp tests/keys/config /etc/wirehub/test")

args = string.format("up ./tests/keys/config private-key tests/keys/%d.sk mode %s", id, mode)

if os.getenv("VALGRIND") then
    execf("WH_LOGPATH=/tmp/log valgrind /usr/local/bin/lua src/tools/cli.lua " .. args)
else
    execf("WH_LOGPATH=/tmp/log wh " .. args)
end

